# Premier Notebook
Loïs GALLAUD 1A Généraliste

## Exercice 1
### Premiers pas et intégration de code

In [1]:
annee = 2023
cours = "ISSD"
print(f"Cours {cours} de l'année {annee}")

Cours ISSD de l'année 2023

## Exercice 3
### Premières manipulation de données avec la librairie *pandas*

In [2]:
import pandas as pd

DATA = pd.read_csv('movie_metadata3.csv', delimiter=';', index_col='movie_title')
DATA.head(n=15) # La méthode head permet d'afficher les n premières lignes du fichier

,director_name,num_critic_for_reviews,duration,actor_1_name,actor_2_name,num_voted_users,facenumber_in_poster,num_user_for_reviews,language,country,content_rating,budget,title_year,imdb_score,genres,plot_keywords
movie_title,,,,,,,,,,,,,,,,
The Shawshank Redemption,Frank Darabont,199,142,Morgan Freeman,Jeffrey DeMunn,1689764,0,4144,English,USA,R,25000000,1994,9.3,Crime|Drama,escape from prison|first person narration|pris...
The Dark Knight,Christopher Nolan,645,152,Christian Bale,Heath Ledger,1676169,0,4667,English,USA,PG-13,185000000,2008,9.0,Action|Crime|Drama|Thriller,based on comic book|dc comics|psychopath|star ...
Inception,Christopher Nolan,642,148,Leonardo DiCaprio,Tom Hardy,1468200,0,2803,English,USA,PG-13,160000000,2010,8.8,Action|Adventure|Sci-Fi|Thriller,ambiguous ending|corporate espionage|dream|sub...
Fight Club,David Fincher,315,151,Brad Pitt,Meat Loaf,1347461,2,2968,English,USA,R,63000000,1999,8.8,Drama,anti establishment|dark humor|fighting|multipl...
Pulp Fiction,Quentin Tarantino,215,178,Bruce Willis,Eric Stoltz,1324680,1,2195,English,USA,R,8000000,1994,8.9,Crime|Drama,black comedy|cunnilingus|neo noir|nonlinear ti...
Forrest Gump,Robert Zemeckis,149,142,Tom Hanks,Siobhan Fallon Hogan,1251222,0,1398,English,USA,PG-13,55000000,1994,8.8,Comedy|Drama,amputee|love|vietnam|vietnam war|war hero
The Lord of the Rings: The Fellowship of the Ring,Peter Jackson,297,171,Christopher Lee,Orlando Bloom,1238746,2,5060,English,New Zealand,PG-13,93000000,2001,8.8,Action|Adventure|Drama|Fantasy,elf|hobbit|middle earth|quest|ring
The Matrix,Lana Wachowski,313,136,Keanu Reeves,Marcus Chong,1217752,3,3646,English,USA,R,63000000,1999,8.7,Action|Sci-Fi,artificial reality|computer|matrix|questioning...
The Lord of the Rings: The Return of the King,Peter Jackson,328,192,Orlando Bloom,Billy Boyd,1215718,2,3189,English,USA,PG-13,94000000,2003,8.9,Action|Adventure|Drama|Fantasy,battle|epic|king|orc|ring
The Godfather,Francis Ford Coppola,208,175,Al Pacino,Marlon Brando,1155770,1,2238,English,USA,R,6000000,1972,9.2,Crime|Drama,crime family|mafia|organized crime|patriarch|r...
The Dark Knight Rises,Christopher Nolan,813,164,Tom Hardy,Christian Bale,1144337,0,2701,English,USA,PG-13,250000000,2012,8.5,Action|Thriller,deception|imprisonment|lawlessness|police offi...
The Lord of the Rings: The Two Towers,Peter Jackson,294,172,Christopher Lee,Orlando Bloom,1100446,1,2417,English,USA,PG-13,94000000,2002,8.7,Action|Adventure|Drama|Fantasy,epic|evil wizard|middle earth|ring|wizard
Se7en,David Fincher,216,127,Morgan Freeman,Brad Pitt,1023511,0,1080,English,USA,R,33000000,1995,8.6,Crime|Drama|Mystery|Thriller,detective|police partner|serial killer|serial ...
The Avengers,Joss Whedon,703,173,Chris Hemsworth,Robert Downey Jr.,995415,3,1722,English,USA,PG-13,220000000,2012,8.1,Action|Adventure|Sci-Fi,alien invasion|assassin|battle|iron man|soldier
Gladiator,Ridley Scott,265,171,Djimon Hounsou,Connie Nielsen,982637,0,2368,English,USA,R,103000000,2000,8.5,Action|Drama|Romance,battlefield|blood|combat|gladiator|roman empire

## Exercice 4
### Jeu simple de données

In [3]:
# Définition d'un jeu simple de données: les températures moyennes par mois à Strasbourg (src: climatdestrasbourg.fr)
temp = [1.9 , 2.9, 7, 10.5, 15, 18.1, 20.1, 19.8, 15.8, 11.2,
5.8, 2.8]
mois = ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin',
'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre']

# On précise l'index de la Serie pandas
s = pd.Series(temp, index=mois)

In [38]:
# On remarque que lors de l'affichage les données sont alignées avec 
# l'index précisé en argument de la méthode Series
print(s)

Janvier       1.9
Fevrier       2.9
Mars          7.0
Avril        10.5
Mai          15.0
Juin         18.1
Juillet      20.1
Aout         19.8
Septembre    15.8
Octobre      11.2
Novembre      5.8
Decembre      2.8
dtype: float64

In [39]:
s.index

Index(['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout',
       'Septembre', 'Octobre', 'Novembre', 'Decembre'],
      dtype='object')

In [40]:
# Que se passe-t-il si on ne précise pas l'index?
s2 = pd.Series(temp)

In [41]:
# On remarque que par défault l'index affiché est [0, ..., n]
print(s2)

0      1.9
1      2.9
2      7.0
3     10.5
4     15.0
5     18.1
6     20.1
7     19.8
8     15.8
9     11.2
10     5.8
11     2.8
dtype: float64

In [42]:
# Pour accéder aux valeurs des index on utilise:
print(s['Janvier'])
print(s2[0]) # /!\ L'index est un entier

1.9
1.9

## Exercice 5
### Manipulation de données avec les *DataFrame* de pandas

In [43]:
# On définit les températures moyennes de chaque de l'année 2018:
temp2018 = [6.7, 1.0, 5.5, 14.6, 17.7, 20.3, 22.7, 22.4, 17.7, 12.5, 6.7, 5.2]

In [44]:
# On crée une DataFrame avec la syntaxe suivante:
df = pd.DataFrame({'Moyenne': temp, 'temp2018': temp2018}, index=mois)
print(df)
print(df.index)
print(df.columns)

           Moyenne  temp2018
Janvier        1.9       6.7
Fevrier        2.9       1.0
Mars           7.0       5.5
Avril         10.5      14.6
Mai           15.0      17.7
Juin          18.1      20.3
Juillet       20.1      22.7
Aout          19.8      22.4
Septembre     15.8      17.7
Octobre       11.2      12.5
Novembre       5.8       6.7
Decembre       2.8       5.2
Index(['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout',
       'Septembre', 'Octobre', 'Novembre', 'Decembre'],
      dtype='object')
Index(['Moyenne', 'temp2018'], dtype='object')

In [49]:
# Il est possible d'ajouter une nouvelle colonne à la DataFrame:
df['Difference'] = ['+', '-','-', '+', '+','+','+','+','+','+','+','+']
print(df)
print(df.dtypes)

           Moyenne  temp2018 Difference
Janvier        1.9       6.7          +
Fevrier        2.9       1.0          -
Mars           7.0       5.5          -
Avril         10.5      14.6          +
Mai           15.0      17.7          +
Juin          18.1      20.3          +
Juillet       20.1      22.7          +
Aout          19.8      22.4          +
Septembre     15.8      17.7          +
Octobre       11.2      12.5          +
Novembre       5.8       6.7          +
Decembre       2.8       5.2          +
Moyenne       float64
temp2018      float64
Difference     object
dtype: object

In [57]:
# On peut récupérer une colonne de la DataFrame comme ceci:
s3 = df['temp2018']
# ou de manière équivalente: s3 = df.temp2018
print(s3)
print(type(s3))

Janvier       6.7
Fevrier       1.0
Mars          5.5
Avril        14.6
Mai          17.7
Juin         20.3
Juillet      22.7
Aout         22.4
Septembre    17.7
Octobre      12.5
Novembre      6.7
Decembre      5.2
Name: temp2018, dtype: float64
<class 'pandas.core.series.Series'>

In [60]:
# Pour récupérer plusieurs colonnes en même temps:
df2 = pd.DataFrame(df, columns=['temp2018', 'Difference'])
print(df2)
print(df2.columns)

           temp2018 Difference
Janvier         6.7          +
Fevrier         1.0          -
Mars            5.5          -
Avril          14.6          +
Mai            17.7          +
Juin           20.3          +
Juillet        22.7          +
Aout           22.4          +
Septembre      17.7          +
Octobre        12.5          +
Novembre        6.7          +
Decembre        5.2          +
Index(['temp2018', 'Difference'], dtype='object')

In [66]:
# Pour récupérer une portion de données:
df3 = df['Fevrier':'Mai'] # ou de manière équivalente df3 = df[1:5]
print(df3)

         Moyenne  temp2018 Difference
Fevrier      2.9       1.0          -
Mars         7.0       5.5          -
Avril       10.5      14.6          +
Mai         15.0      17.7          +